from enum import Enum


class EventType(str, Enum):
    USER_PROMPT = "USER_PROMPT"
    DOCUMENT_CONTEXT = "DOCUMENT_CONTEXT"
    AGENT_PLAN = "AGENT_PLAN"
    TOOL_CALL = "TOOL_CALL"
    TOOL_RESULT = "TOOL_RESULT"
    FINAL_RESPONSE = "FINAL_RESPONSE"
    POLICY_DECISION = "POLICY_DECISION"
    INCIDENT_REPORT = "INCIDENT_REPORT"


class ActorType(str, Enum):
    USER = "USER"
    AI_AGENT = "AI_AGENT"
    TOOL = "TOOL"
    SYSTEM = "SYSTEM"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ResponsibilityType(str, Enum):
    USER_DIRECTED = "USER_DIRECTED"
    AGENT_INDUCED = "AGENT_INDUCED"
    DOCUMENT_INDUCED = "DOCUMENT_INDUCED"
    TOOL_RESULT_INDUCED = "TOOL_RESULT_INDUCED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    UNKNOWN = "UNKNOWN"


class ToolName(str, Enum):
    READ_FILE = "READ_FILE"
    WRITE_FILE = "WRITE_FILE"
    EXTERNAL_HTTP_POST = "EXTERNAL_HTTP_POST"
    EXTERNAL_HTTP_GET = "EXTERNAL_HTTP_GET"
    RUN_COMMAND = "RUN_COMMAND"
    NONE = "NONE"
